export const userAccessList = [
  {
    id: '1',
    name: '会员管理',
    parentId: '0',
    type: '0',
    checked: 0,
    resourceLevel: 1,
    resourceCode: '',
    icon: '6',
    sort: 1,
    disabled: 0,
    children: [
      {
        id: '1801',
        name: '会员列表',
        parentId: '18',
        type: '0',
        checked: 0,
        resourceLevel: 1,
        resourceCode: '',
        icon: '2',
        sort: 1,
        disabled: 0,
        children: [],
        enName: '',
        path: '',
        pids: ['18'],
      },
      {
        id: '1802',
        name: '会员配置',
        parentId: '18',
        type: '0',
        checked: 0,
        resourceLevel: 1,
        resourceCode: '',
        icon: '',
        sort: 3,
        disabled: 0,
        children: [],
        enName: '',
        path: '',
        pids: ['18'],
      },
    ],
  },
  {
    id: '4',
    name: '系统管理',
    parentId: '0',
    type: '0',
    checked: 0,
    resourceLevel: 1,
    resourceCode: '',
    icon: '3',
    sort: 11,
    disabled: 0,
    children: [
      {
        id: '1001',
        name: '系统账号',
        parentId: '10',
        type: '0',
        checked: 0,
        resourceLevel: 1,
        resourceCode: '',
        icon: '',
        sort: 1,
        disabled: 0,
        children: [],
        enName: '',
        path: '',
        pids: ['10'],
      },
      {
        id: '1002',
        name: '角色权限',
        parentId: '10',
        type: '0',
        checked: 0,
        resourceLevel: 1,
        resourceCode: '',
        icon: '',
        sort: 2,
        disabled: 0,
        children: [],
        enName: '',
        path: '',
        pids: ['10'],
      },
      {
        id: '1003',
        name: '访问授权',
        parentId: '10',
        type: '0',
        checked: 0,
        resourceLevel: 1,
        resourceCode: '',
        icon: '',
        sort: 3,
        disabled: 0,
        children: [],
        enName: '',
        path: '',
        pids: ['10'],
      },
      {
        id: '1006',
        name: '日志管理',
        parentId: '10',
        type: '0',
        checked: 0,
        resourceLevel: 1,
        resourceCode: '',
        icon: '',
        sort: 6,
        disabled: 0,
        children: [],
        enName: '',
        path: '',
        pids: ['10'],
      },
    ],
  },
]
